apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web/certificate.yaml
  - web/config.yaml
  - web/service.yaml
  - web/deployment.yaml
  - web/route.yaml
  - api/certificate.yaml
  - api/service.yaml
  - api/deployment.yaml
  - api/route.yaml
