apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amazon-cloudwatch
secretGenerator:
  - name: fluent-bit-cloudwatch-access
    envs:
      - aws.credentials.env
resources:
  - namespace.yaml
  - config.yaml
  - deployment.yaml
patchesJson6902:
  - target:
      version: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: fluent-bit-role-binding
    patch: |
      - op: add
        path: /subjects[0]/namespace
        value: amazon-cloudwatch
