name: Fixing code style

on:
  push:
    branches:
      - staging

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    defaults:
      run:
        shell: bash
        working-directory: services/web
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running code style fixes
        run: pnpm run fix

      - name: Preparing merge
        id: prepare
        run: |
          if ! git diff --quiet
          then
            TEMP_BRANCH=$(uuidgen)
            echo "::set-output name=TEMP_BRANCH::$TEMP_BRANCH"
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git checkout -b $TEMP_BRANCH
            git add --update
            git commit --message "github-actions: fix code style"
            git push origin $TEMP_BRANCH
          else
            echo "Nothing to commit!"
          fi

      - name: Creating pull request
        if: steps.prepare.outputs.TEMP_BRANCH != null
        id: create-pull
        uses: ./.github/actions/create-pull
        with:
          base: staging
          head: ${{ steps.prepare.outputs.TEMP_BRANCH  }}
          title: 'github-actions: fix code style'

      - name: Merging pull request
        if: steps.create-pull.outputs.pull_number != null
        uses: ./.github/actions/merge-pull
        with:
          pull_number: ${{ steps.create-pull.outputs.pull_number }}
          merge_method: 'github_squash'
          delete_head: true

  api:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
    defaults:
      run:
        shell: bash
        working-directory: services/api
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
