name: Building and pushing container images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Creating new tag
        id: tag
        run: |
          tag=$(date +"%d.%m.%Y")
          echo "::set-output name=tag::$tag"

  build-and-push-web:
    needs:
      - should-run
      - create-tag
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true' ||
      github.event_name == 'workflow_dispatch'
    environment:
      name: DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Setting up Quick Emulator (QEMU)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64,linux/amd64

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Logging in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Building and pushing container image
        uses: docker/build-push-action@v3
        with:
          context: services/web
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:web.latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:web.${{ needs.create-tag.outputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:web.cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:web.cache,mode=max

  build-and-push-api:
    needs:
      - should-run
      - create-tag
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true' ||
      github.event_name == 'workflow_dispatch'
    environment:
      name: DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Setting up Quick Emulator (QEMU)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64,linux/amd64

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Logging in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Building and pushing container image
        uses: docker/build-push-action@v3
        with:
          context: services/api
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:api.latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:api.${{ needs.create-tag.outputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:api.cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/image-data-hiding:api.cache,mode=max
