name: Merge main

on:
  workflow_dispatch:

jobs:
  test-web:
    uses: ./.github/workflows/test-web.yaml

  test-api:
    uses: ./.github/workflows/test-api.yaml

  merge:
    needs:
      - test-web
      - test-api
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          ENV_CONTEXT: ${{ toJSON(env) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: echo "Done"

      - name: Creating pull request
        uses: ./.github/actions/create-pull
        id: create-pull
        with:
          base: main
          head: staging
          title: 'github-actions: merge staging into main'

      - name: Merging pull request
        uses: ./.github/actions/merge-pull
        with:
          pull_number: ${{ steps.create-pull.outputs.pull_number }}
