name: Should run reuseable workflow

on:
  workflow_call:
    inputs:
      projects:
        description: The projects to match against
        type: string
        required: true
    outputs:
      result:
        description: JSON result - One boolean property for each input project
        value: ${{ jobs.main.outputs.result }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ toJSON(steps.match.outputs) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run the match script
        id: match
        run: ./.github/match.sh "${{ inputs.projects }}"

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: env
